services:
  - type: web
    name: todo-app
    env: node
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
    plan: free
